name: Auto Scrape & Update M3U

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Scraper Script
        run: py -3 scraper.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add channels.m3u
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update channels.m3u [skip ci]" && git push)
