- name: Check for changes and commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Prothome file-ti git add kore nei, jate tracking shuru hoy
          git add channels.m3u
          
          # Dekhi kono change ache kina
          if git diff --staged --quiet; then
            echo "No changes detected in the playlist. Skipping commit."
          else
            echo "Changes detected! Committing new playlist..."
            git commit -m "Auto-update M3U playlist [skip ci]"
            git push
          fi
